# 字体与文字密度

# 使用包含常用图标字符的 Meslo 等宽字体。
font_family MesloLGSDZ Nerd Font
# 自动选择与主字体匹配的粗体字形。
bold_font auto
# 自动选择与主字体匹配的斜体字形。
italic_font auto
# 自动选择与主字体匹配的粗斜体字形。
bold_italic_font auto
# 将终端字体大小设置为 13 磅。
font_size 13
